before:
  hooks:
    - go mod download

builds:
- main: ./main.go
  env:
  - CGO_ENABLED=0
  goos:
  - windows
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  ldflags:
  - "-s"
  - "-w"
  - "-X github.com/open-policy-agent/conftest/internal/commands.version={{.Version}}"
  - "-X github.com/open-policy-agent/conftest/internal/commands.commit={{.ShortCommit}}"
  - "-X github.com/open-policy-agent/conftest/internal/commands.date={{.Date}}"

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
      - LICENSE
      - README.md
      - plugin/*.sh

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
- tap:
    owner: instrumenta
    name: homebrew-instrumenta
  folder: Formula
  description: "Test your configuration using Open Policy Agent"
  homepage: "https://github.com/open-policy-agent/conftest"
  test: |
    system "#{bin}/conftest --version"

scoop:
  bucket:
    owner: instrumenta
    name: scoop-instrumenta
  description: "Test your configuration using Open Policy Agent"
  homepage: "https://github.com/open-policy-agent/conftest"

nfpms:
  - bindir: /usr/bin
    description: "Test your configuration using Open Policy Agent"
    formats:
      - deb
      - rpm
    homepage: https://github.com/open-policy-agent/conftest
    maintainer: jpreese <john@reese.dev>
    license: Apache-2.0
