name: pull-request

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'

      - name: lint
        run: make lint

      - name: build
        run: make build

      - name: unit tests
        run: make test

      - name: test examples
        run: make test-examples

      - name: test acceptance
        run: make test-acceptance
